#!/usr/bin/perl -w

#################################################################3
#
# snortban
#
# Francesc Guasch - frankie etsetb upc edu
#

use strict;
use Getopt::Long;
use Proc::PID::File;
use File::Tail;

$|=1;

my $DEBUG;
my $LOGFILE = "/var/log/snort/alert";
my $BANFILE = "$LOGFILE.ban";
my $TIMEOUT = 30;

my $VERSION = '0.01';

{

    my $version;
    my $help;
    
    GetOptions ( 
            debug => \$DEBUG 
        , logfile => \$LOGFILE 
        , banfile => \$BANFILE
        , timeout => \$TIMEOUT
        , version => \$version
        ,    help => \$help
    );
    
    if ($version) {
            print "$0 v$VERSION\n";
            exit 0;
    }
    
    if ($help) {
        print "$0 [--debug] [--help] [--logfile=$LOGFILE] [--timeout=$TIMEOUT]"
            ." [--banfile=$BANFILE]\n";
        exit 0;

    }

}
my $PROC = Proc::PID::File->new();

########################################################################

sub tail {
		warn "Opening $LOGFILE -> $BANFILE\n";
        print "Opening $LOGFILE\n"          if $DEBUG;
		die "Missing $LOGFILE\n"
			if ! -e $LOGFILE;

		my $f_tail = File::Tail->new($LOGFILE)
			or die "$! $LOGFILE";

        print "Output to $BANFILE\n"        if $DEBUG;
        open my $f_ban,'>>', $BANFILE                 or die "$! $BANFILE";

        my $stdout = select($f_ban);
        $|=1;
        select($stdout);

        my $cnt = 0;
        my $former;
        while (my $line = $f_tail->read) {
            if  ($line !~ /Priority: \d/) {
                $former = $line;
                next;
            }
            next if ! $former;
            chomp $line;
            my $next=$f_tail->read;
            chomp $next;
            $next =~ s/.*?\.\d+ //;
            my $info = "".localtime(time)." $line $next $former";
            print $f_ban $info;
            print $info     if $DEBUG;
        }
        close $f_tail;
        close $f_ban;
}

sub start  {

	die "Already running\n" if Proc::PID::File->running();

	print "Starting $0\n";

	for (;;) {
		tail();
	}
}

################################################################################

start();
