#!/usr/bin/perl -w

#################################################################3
#
# snortban
#
# Francesc Guasch - frankie etsetb upc edu
#

use strict;
use Getopt::Long;
use Proc::PID::File;

$|=1;

my $DEBUG;
my $LOGFILE = "/var/log/snort/alert";
my $BANFILE = "$LOGFILE.ban";
my $TIMEOUT = 30;

my $VERSION = '0.01';

{

    my $version;
    my $help;
    
    GetOptions ( 
            debug => \$DEBUG 
        , logfile => \$LOGFILE 
        , banfile => \$BANFILE
        , timeout => \$TIMEOUT
        , version => \$version
        ,    help => \$help
    );
    
    if ($version) {
            print "$0 v$VERSION\n";
            exit 0;
    }
    
    if ($help) {
        print "$0 [--debug] [--help] [--logfile=$LOGFILE] [--timeout=$TIMEOUT]"
            ." [--banfile=$BANFILE]\n";
        exit 0;

    }

}
my $PROC = Proc::PID::File->new();
my $F_TAIL;
my $F_BAN;

########################################################################

sub tail {
        print "Opening $LOGFILE\n"          if $DEBUG;
		die "Missing $LOGFILE\n"
			if ! -e $LOGFILE;
        open $F_TAIL ,'-|',"tail -f $LOGFILE"
            or die "I can't tail -f $LOGFILE$!";

        print "Output to $BANFILE\n"        if $DEBUG;
        open $F_BAN,'>>', $BANFILE                 or die "$! $BANFILE";

        my $stdout = select($F_BAN);
        $|=1;
        select($stdout);

        my $cnt = 0;
        my $former;
        while (my $line = <$F_TAIL>) {
            if  ($line !~ /Priority: \d/) {
                $former = $line;
                next;
            }
            next if ! $former;
            chomp $line;
            my $next=<$F_TAIL>;
            chomp $next;
            $next =~ s/.*?\.\d+ //;
            my $info = "".localtime(time)." $line $next $former";
            print $F_BAN $info;
            print $info     if $DEBUG;
        }
        close $F_TAIL;
        close $F_BAN;
}

sub start  {

	die "Already running\n" if Proc::PID::File->running();

	print "Starting $0\n";

	local $SIG{ALRM} = sub { 
						warn "Closing tail"; 
						close $F_TAIL; close $F_BAN;
						tail();
	};
	alarm($TIMEOUT);
	tail();
}

################################################################################

start();
